DROP TABLE IF EXISTS user_stats CASCADE;

CREATE TABLE IF NOT EXISTS user_stats (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    focus INTEGER NOT NULL DEFAULT 0,
    completed_quests INTEGER NOT NULL DEFAULT 0,
    missed_quests INTEGER NOT NULL DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT now()
);
