DROP TABLE IF EXISTS user_badges CASCADE;

CREATE TABLE IF NOT EXISTS user_badges (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  badge_id INTEGER REFERENCES badges(id) ON DELETE SET NULL
);
